### ISSUE TITLE
Cannot require 'string_undump' on AmazonLinux and CentOS

### ISSUE THREAD

**Issue by fujiwara** [tadd/string_undump#2]
Hi.
I got errors at `require 'string_undump'` on some environments (AmazonLinux 2018.03 system ruby and CentOS7 SCL).
That is not reproduced on debian stretch and ubuntu 16.04.

https://github.com/coinbase/terraform-landscape/issues/78

## How to reproduce

```console
$ docker run -it --rm amazonlinux:2018.03 bash
bash-4.2# yum -y install ruby24 ruby24-devel gcc make
bash-4.2# ruby -v
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux-gnu]
bash-4.2# gem install string_undump
....
1 gem installed
bash-4.2# ruby -e "require 'string_undump'"
/usr/local/share/ruby/gems/2.4/gems/string_undump-0.1.1/lib/string_undump.rb:1:in `require_relative': cannot load such file -- /usr/local/share/ruby/gems/2.4/gems/string_undump-0.1.1/lib/string_undump/string_undump.so (LoadError)
	from /usr/local/share/ruby/gems/2.4/gems/string_undump-0.1.1/lib/string_undump.rb:1:in `<top (required)>'
	from /usr/share/ruby/vendor_ruby/2.4/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /usr/share/ruby/vendor_ruby/2.4/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/share/ruby/vendor_ruby/2.4/rubygems/core_ext/kernel_require.rb:39:in `require'
	from -e:1:in `<main>'
```

```console
$ docker run -it --rm centos:7 bash
[root@da715e109b6b /]# yum -y install centos-release-scl-rh centos-release-scl
[root@da715e109b6b /]# yum --enablerepo=centos-sclo-rh -y install rh-ruby24 rh-ruby24-ruby-devel gcc make
[root@da715e109b6b /]# scl enable rh-ruby24 bash
[root@da715e109b6b /]# ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
[root@da715e109b6b /]# gem install string_undump
...
1 gem installed
[root@da715e109b6b /]# ruby -e "require 'string_undump'"
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/string_undump-0.1.1/lib/string_undump.rb:1:in `require_relative': cannot load such file -- /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/string_undump-0.1.1/lib/string_undump/string_undump.so (LoadError)
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/string_undump-0.1.1/lib/string_undump.rb:1:in `<top (required)>'
	from /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
	from -e:1:in `<main>'
```

**Comment by tadd** [comment]
Oops, I've missed notice from GitHub that sent over 10 days ago... sorry.
And thanks for your interests and using this gem!

This repo is not maintained well, but I hope I can handle this issue in incoming holiday season.

I guess this will be solved with not using `require_relative` but `require` in lib/string_undump.rb, although I'm not confident that it is the right direction.  I need to research more.
